alias open='xdg-open'
alias vnc='xtightvncviewer'
#git stuff
alias gs='git status '
alias ga='git add '
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias go='git checkout '
alias gm='git merge '
